services:
    m6.data_collector.wsclient:
        class: M6Web\Bundle\WSClientBundle\DataCollector\WSClientDataCollector
        tags:
            - { name: data_collector, template: 'M6WebWSClientBundle:Collector:wsclient', id: 'wsclient' }
            - { name: kernel.event_listener, event: wsclient.command, method: onWSClientCommand }